"""
Django settings for config project - WebGIS de Coleta de Campo

Generated by 'django-admin startproject' using Django 4.2.7.
"""

import os
from pathlib import Path
from decouple import config


# Configuração GDAL para Windows (OSGeo4W)
#if os.name == 'nt':  # Se for Windows
#    import sys
#    
#    OSGEO4W = r"C:\Users\fabio.dlima\AppData\Local\Programs\OSGeo4W"
#    
#    if os.path.isdir(OSGEO4W):
#        # Adiciona MÚLTIPLOS diretórios ao PATH (ordem importante!)
#        osgeo_paths = [
#            os.path.join(OSGEO4W, 'bin'),
#            os.path.join(OSGEO4W, 'apps', 'gdal', 'bin'),
#            os.path.join(OSGEO4W, 'apps', 'proj', 'bin'),
#            os.path.join(OSGEO4W, 'apps', 'Python39', 'Scripts'),
#        ]
        
        # Adiciona todos os caminhos ao PATH
#        for path in osgeo_paths:
#            if os.path.isdir(path):
#                os.environ['PATH'] = path + ';' + os.environ['PATH']
#        
#        # Configura as variáveis de ambiente
#        os.environ['OSGEO4W_ROOT'] = OSGEO4W
#        os.environ['GDAL_DATA'] = os.path.join(OSGEO4W, 'share', 'gdal')
#        os.environ['PROJ_LIB'] = os.path.join(OSGEO4W, 'share', 'proj')
#        
#        # Define explicitamente o caminho das bibliotecas
#        GDAL_LIBRARY_PATH = os.path.join(OSGEO4W, 'bin', 'gdal311.dll')
#        GEOS_LIBRARY_PATH = os.path.join(OSGEO4W, 'bin', 'geos_c.dll')

        
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-sua-chave-secreta-aqui-mude-em-producao')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django.contrib.gis',  # GeoDjango
    
    # Third party
    'rest_framework',
    'corsheaders',
    'django_filters',
    
    # Local apps
    'coleta',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# Usando SQLite para desenvolvimento rápido
# Para usar PostgreSQL + PostGIS em produção, comente a configuração abaixo e descomente a segunda
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite padrão para desenvolvimento
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Para usar PostgreSQL + PostGIS em produção, descomente abaixo:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': config('DB_NAME', default='webgis_db'),
#         'USER': config('DB_USER', default='postgres'),
#         'PASSWORD': config('DB_PASSWORD', default='postgres'),
#         'HOST': config('DB_HOST', default='localhost'),
#         'PORT': config('DB_PORT', default='5432'),
#     }
# }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# CORS Configuration (permitir acesso de diferentes origens)
CORS_ALLOW_ALL_ORIGINS = True  # Em produção, especifique os domínios permitidos
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:3000",
#     "http://localhost:8000",
# ]

# GeoDjango Configuration (descomente quando usar PostGIS)
# GEOS_LIBRARY_PATH = None  # Será detectado automaticamente
# GDAL_LIBRARY_PATH = None  # Será detectado automaticamente
