# Generated by Django 4.2.7 on 2025-11-06 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_imovel', models.CharField(help_text='Identificação única do imóvel', max_length=50, verbose_name='Número do Imóvel')),
                ('numero_hidrometro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Hidrômetro')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endereço Completo')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(help_text='Latitude do imóvel (ex: -1.4558)', verbose_name='Latitude')),
                ('longitude', models.FloatField(help_text='Longitude do imóvel (ex: -48.4902)', verbose_name='Longitude')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações de Campo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='imoveis/%Y/%m/%d/', verbose_name='Foto do Imóvel')),
                ('data_coleta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Coleta')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Registro Ativo')),
                ('agente_coleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imoveis_coletados', to=settings.AUTH_USER_MODEL, verbose_name='Agente de Coleta')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-data_coleta'],
                'indexes': [models.Index(fields=['numero_imovel'], name='coleta_imov_numero__12cad2_idx'), models.Index(fields=['data_coleta'], name='coleta_imov_data_co_060b85_idx')],
            },
        ),
    ]
